"""Loading and querying the simulator <-> real-game card map.

The map itself is card_map.json, generated by tools/gen_card_map.py. This
module is the only sanctioned way to read it, because it is where the
DEFINED BEHAVIOUR for a card the simulator does not have is implemented --
and that behaviour is the whole point of having a map instead of a dict
comprehension over the registry.

THE THREE CASES, AND WHY NONE OF THEM IS A SILENT FALLBACK
-----------------------------------------------------------
A vision system that guesses when it is unsure produces a state estimate that
is confidently wrong, which is strictly worse than one that is loudly
incomplete: the engine has no way to represent doubt (no mask channel, no
NaN -- see contracts.py), so anything uncertain that gets through this layer
becomes indistinguishable from fact downstream.

  1. Mapped card. Normal path.

  2. Known real card, `sim_id: null`. The card exists in the real game and
     is not implemented in this simulator. resolve() returns it with
     card_sim_id = UNKNOWN_CARD_SIM_ID. The event is still emitted, still
     timestamped, still localised -- the bridge declines to inject it and
     raises the "unmapped_placement" flag, and the opponent-elixir model
     still cannot debit a cost it does not know. That combination is exactly
     what makes the divergence metric grow, which is the correct outcome: the
     estimate genuinely is less trustworthy from that moment on.

  3. A name that is in NO row of the map. This is not an unimplemented card,
     it is a bug -- either the detector emitted a label outside its own
     vocabulary, or the map is stale. resolve() raises UnknownCardError.
     Returning -1 here would collapse case 3 into case 2 and hide a real
     defect behind a mechanism designed for an expected one.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

_MAP_PATH = Path(__file__).resolve().parent / "card_map.json"

# Kept in sync with contracts.UNKNOWN_CARD_SIM_ID, duplicated as a literal
# only so this package imports cleanly when used standalone by tooling.
UNKNOWN_CARD_SIM_ID = -1


class UnknownCardError(KeyError):
    """A card name that appears in no row of card_map.json. See case 3."""


class DeckNotRepresentableError(ValueError):
    """A deck contains a card the simulator cannot represent.

    Raised by require_sim_deck(). A ClashEnv can only be constructed from
    eight real CardRegistry ids that pass validate_deck_slots, so a deck
    containing an unimplemented card cannot be simulated AT ALL -- not
    approximately, not with a placeholder. Substituting some other card would
    produce an estimator that silently models a different game than the one
    being played, so this refuses to start and names the offending card.
    """


@dataclass(frozen=True)
class CardEntry:
    slug: str
    real_name: str
    sim_id: int | None
    sim_evo_id: int | None
    cost: float
    is_spell: bool
    is_building: bool
    is_champion: bool
    is_hero: bool
    real_verified: bool
    real_only: bool
    needs_review: bool

    @property
    def in_simulator(self) -> bool:
        return self.sim_id is not None

    def sim_id_for(self, evolution: bool = False) -> int:
        """Resolve to the id to hand the engine.

        An evolved play whose Evolution is not registered falls back to the
        base id rather than failing: the base card is a strictly better
        approximation of an evolved card than nothing at all, and unlike the
        unmapped-card case there is no ambiguity about WHICH card was played.
        """
        if evolution and self.sim_evo_id is not None:
            return self.sim_evo_id
        return self.sim_id if self.sim_id is not None else UNKNOWN_CARD_SIM_ID


def slugify(name: str) -> str:
    """Must match tools/gen_card_map.py's slugify exactly."""
    return re.sub(r"[^a-z0-9]", "", name.lower())


@lru_cache(maxsize=1)
def _raw() -> dict:
    if not _MAP_PATH.exists():
        raise FileNotFoundError(
            f"card_map.json not found at {_MAP_PATH}. Generate it with "
            "perception/tools/gen_card_map.py."
        )
    return json.loads(_MAP_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def _entries() -> dict[str, CardEntry]:
    out: dict[str, CardEntry] = {}
    for slug, row in _raw()["cards"].items():
        entry = CardEntry(
            slug=slug,
            real_name=row["real_name"],
            sim_id=row.get("sim_id"),
            sim_evo_id=row.get("sim_evo_id"),
            cost=float(row.get("cost", 0.0)),
            is_spell=bool(row.get("is_spell", False)),
            is_building=bool(row.get("is_building", False)),
            is_champion=bool(row.get("is_champion", False)),
            is_hero=bool(row.get("is_hero", False)),
            real_verified=bool(row.get("real_verified", False)),
            real_only=bool(row.get("real_only", False)),
            needs_review=bool(row.get("needs_review", False)),
        )
        out[slug] = entry
        for alias in row.get("aliases", ()):
            out[slugify(alias)] = entry
    return out


def resolve(card_real_name: str) -> CardEntry:
    """Look up a detector label. Raises UnknownCardError -- see case 3."""
    entry = _entries().get(slugify(card_real_name))
    if entry is None:
        raise UnknownCardError(
            f"{card_real_name!r} appears in no row of card_map.json. This is a "
            "stale map or a detector label outside its own vocabulary -- not an "
            "unimplemented card (those carry sim_id: null). Add the row, or fix "
            "the label set."
        )
    return entry


def detector_vocabulary() -> tuple[str, ...]:
    """Card slugs the detector is allowed to emit.

    Filtered on real_verified, so the ~11 registry entries whose real-game
    counterpart nobody has confirmed (Spirit Empress, the Hero cards) cannot
    be predicted at all until someone ticks the box. A classifier with dead
    classes in its label set does not merely waste capacity, it produces
    confident false positives on visually adjacent real cards.
    """
    return tuple(sorted({e.slug for e in _entries().values() if e.real_verified}))


def require_sim_deck(card_real_names: list[str]) -> list[int]:
    """Real deck -> eight simulator ids, or refuse.

    See DeckNotRepresentableError for why this refuses rather than
    substitutes.
    """
    resolved = [(name, resolve(name)) for name in card_real_names]
    missing = [name for name, entry in resolved if not entry.in_simulator]
    if missing:
        raise DeckNotRepresentableError(
            "Deck cannot be simulated -- no CardRegistry id for: "
            + ", ".join(sorted(missing))
            + ". The simulator cannot represent this deck, so the estimator "
            "would be modelling a different game than the one being played. "
            "Either implement the card in CardRegistry.h, or record with a "
            "deck the simulator covers."
        )
    return [entry.sim_id_for() for _name, entry in resolved]


def review_queue() -> tuple[CardEntry, ...]:
    """Rows a human still has to confirm. Surfaced by the README and tests."""
    seen: dict[str, CardEntry] = {}
    for entry in _entries().values():
        if entry.needs_review:
            seen[entry.slug] = entry
    return tuple(sorted(seen.values(), key=lambda e: e.slug))
