"""Loading and querying the simulator <-> real-game card map.

The map is card_map.json, generated by tools/gen_card_map.py. This module is
the only sanctioned reader, because it implements the defined behaviour for a
card the simulator does not have. A guess here would be confidently wrong, and
the engine cannot represent doubt (contracts.py), so none of the three cases
falls back silently:

  1. Mapped card. Normal path.

  2. Known real card, `sim_id: null`: in the real game, not in the simulator.
     resolve() returns it with card_sim_id = UNKNOWN_CARD_SIM_ID. The event is
     still emitted, timestamped and localised; the bridge declines to inject it
     and raises "unmapped_placement", and the opponent-elixir model cannot
     debit it. The divergence metric then grows, correctly: the estimate is
     less trustworthy from that moment.

  3. A name in no row of the map: a bug (a detector label outside its own
     vocabulary, or a stale map). resolve() raises UnknownCardError rather
     than collapsing it into case 2.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

_MAP_PATH = Path(__file__).resolve().parent / "card_map.json"

# contracts.UNKNOWN_CARD_SIM_ID, duplicated as a literal so this package
# imports standalone for tooling.
UNKNOWN_CARD_SIM_ID = -1


class UnknownCardError(KeyError):
    """A card name that appears in no row of card_map.json. See case 3."""


class DeckNotRepresentableError(ValueError):
    """A deck contains a card the simulator cannot represent.

    Raised by require_sim_deck(). A ClashEnv needs eight real CardRegistry ids,
    so such a deck cannot be simulated at all, and a substitute card would
    model a different game. Refuses and names the card.
    """


@dataclass(frozen=True)
class CardEntry:
    slug: str
    real_name: str
    sim_id: int | None
    sim_evo_id: int | None
    cost: float
    is_spell: bool
    is_building: bool
    is_champion: bool
    is_hero: bool
    real_verified: bool
    real_only: bool
    needs_review: bool

    @property
    def in_simulator(self) -> bool:
        return self.sim_id is not None

    def sim_id_for(self, evolution: bool = False) -> int:
        """Resolve to the id to hand the engine. An evolved play whose Evolution
        is not registered falls back to the base id: the base card approximates
        it well, and there is no ambiguity about which card was played.
        """
        if evolution and self.sim_evo_id is not None:
            return self.sim_evo_id
        return self.sim_id if self.sim_id is not None else UNKNOWN_CARD_SIM_ID


def slugify(name: str) -> str:
    """Must match tools/gen_card_map.py's slugify exactly."""
    return re.sub(r"[^a-z0-9]", "", name.lower())


@lru_cache(maxsize=1)
def _raw() -> dict:
    if not _MAP_PATH.exists():
        raise FileNotFoundError(
            f"card_map.json not found at {_MAP_PATH}. Generate it with "
            "perception/tools/gen_card_map.py."
        )
    return json.loads(_MAP_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def _entries() -> dict[str, CardEntry]:
    out: dict[str, CardEntry] = {}
    for slug, row in _raw()["cards"].items():
        entry = CardEntry(
            slug=slug,
            real_name=row["real_name"],
            sim_id=row.get("sim_id"),
            sim_evo_id=row.get("sim_evo_id"),
            cost=float(row.get("cost", 0.0)),
            is_spell=bool(row.get("is_spell", False)),
            is_building=bool(row.get("is_building", False)),
            is_champion=bool(row.get("is_champion", False)),
            is_hero=bool(row.get("is_hero", False)),
            real_verified=bool(row.get("real_verified", False)),
            real_only=bool(row.get("real_only", False)),
            needs_review=bool(row.get("needs_review", False)),
        )
        out[slug] = entry
        for alias in row.get("aliases", ()):
            out[slugify(alias)] = entry
    return out


def resolve(card_real_name: str) -> CardEntry:
    """Look up a detector label. Raises UnknownCardError -- see case 3."""
    entry = _entries().get(slugify(card_real_name))
    if entry is None:
        raise UnknownCardError(
            f"{card_real_name!r} appears in no row of card_map.json. This is a "
            "stale map or a detector label outside its own vocabulary -- not an "
            "unimplemented card (those carry sim_id: null). Add the row, or fix "
            "the label set."
        )
    return entry


def detector_vocabulary() -> tuple[str, ...]:
    """Card slugs the detector may emit, filtered on real_verified, so unconfirmed
    registry entries (Spirit Empress, the Hero cards) cannot be predicted. Dead
    classes produce confident false positives on visually adjacent real cards.
    """
    return tuple(sorted({e.slug for e in _entries().values() if e.real_verified}))


def require_sim_deck(card_real_names: list[str]) -> list[int]:
    """Real deck -> eight simulator ids, or refuse (see
    DeckNotRepresentableError).
    """
    resolved = [(name, resolve(name)) for name in card_real_names]
    missing = [name for name, entry in resolved if not entry.in_simulator]
    if missing:
        raise DeckNotRepresentableError(
            "Deck cannot be simulated -- no CardRegistry id for: "
            + ", ".join(sorted(missing))
            + ". The simulator cannot represent this deck, so the estimator "
            "would be modelling a different game than the one being played. "
            "Either implement the card in CardRegistry.h, or record with a "
            "deck the simulator covers."
        )
    return [entry.sim_id_for() for _name, entry in resolved]


def review_queue() -> tuple[CardEntry, ...]:
    """Rows a human still has to confirm. Surfaced by the README and tests."""
    seen: dict[str, CardEntry] = {}
    for entry in _entries().values():
        if entry.needs_review:
            seen[entry.slug] = entry
    return tuple(sorted(seen.values(), key=lambda e: e.slug))
